services:
  postgres:
    image: postgres:16-alpine
    container_name: quranic-app-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_dev_password
      POSTGRES_DB: quranic_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
